baseURL = 'https://rezept.nv.gw/'
languageCode = 'de-DE'
title = 'Rezept'
theme = 'PaperMod'

params.hideSummary = true
params.disableSpecial1stPost = true

copyright = "&copy; Nina van der Linden 2023 |"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
